---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
'Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  

'Beware the Jabberwock, my son!  



## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
I left you in the morning,   
And in the morning glow,  
You walked a way beside me  
To make me sad to go.  
Do you know me in the gloaming,  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!"  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
He was so proud of his little girl.  
It was her very first day of school.  
He walked with her to school that day,  
And she held his hand all the way.  
They walked together quiet and sad,  
A little girl and her loving dad.  
Into the school her father led,  
But he almost cried when she said,  
"Daddy, Daddy, please don't go.  
Don't leave me here all alone.  
I'll miss you if you go away,
And I might need you; can't you stay?"  
"Little Daughter, please don't cry.  
You'll be okay, so dry your eyes.  
You have our memories in your heart.  
We're together though we're apart."  

He sat up front on her wedding day  
And cried as his daughter walked away.  
Later that night he watched her dance.  
He sat there waiting for his chance.  

